language: generic

<<<<<<< HEAD
os: linux

env:
  - TARGET_PLUGIN=GMIC

before_install:
  - sudo docker run -it -v $(pwd):/sources -e TARGET_PLUGIN="${TARGET_PLUGIN}"  photoflow/docker-centos7-gimp bash /sources/travis/build-linux.sh
  - ls -lh out/*.*
  - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
  - bash  ./upload_rotate.sh "continuous" out/*.AppImage >& /dev/null
  - bash  ./upload_rotate.sh "continuous" out/*.hash >& /dev/null
=======
os: osx
osx_image: xcode8.3

env:
  - TARGET_PLUGIN=ResynthesizerPlugin

before_install:
  - brew update >& /dev/null && brew install ccache
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - bash ./travis/build-osx.sh
>>>>>>> 6ce44fd25caf64b56cc2133e270c5b4f94eb7afc

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
