language: generic

osx_image: xcode9.4

os:
  #- linux
  - osx

env:
  #- TARGET_PLUGIN=PhFGimp
  - TARGET_PLUGIN=GMIC

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ccache; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 120 bash ./travis/build-osx.sh; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
