language: generic
os:
  - linux
  - osx

env:
  - TARGET_PLUGIN=PhFGimp
  - TARGET_PLUGIN=GMIC

#env:
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env: MACOSX_DEPLOYMENT_TARGET=10.8
          before_script:
            - source ./environment.sh
            - brew update
            - mkdir plugins
            - bash ./build-common-osx.sh
            - bash ./${TARGET_PLUGIN}/build-osx.sh
            #
            - rm -rf plugins-fixed
            - curl -L https://download.gimp.org/mirror/pub/gimp/v2.10/osx/gimp-2.10.6-x86_64.dmg -O
            - hdiutil attach gimp-2.10.6-x86_64.dmg >& attach.log
            - export MOUNT_POINT=$(cat attach.log | tr "\t" "\n" | tail -n 1)
            - export GIMP_BUNDLE="$(find "$MOUNT_POINT" -depth 1 -name "*.app" | tail -n 1)"
            - rm -f /tmp/gimp.app
            - ln -s "$GIMP_BUNDLE" /tmp/gimp.app
            - bash ./fix-dylib.sh ${TARGET_PLUGIN} "$(basename "$GIMP_BUNDLE")"
            - ls plugins-fixed
            - cd plugins-fixed
            - tar czvf ../${TARGET_PLUGIN}-Gimp-2.10.6-OSX.tgz ??*
            - cd ..
            #
            - rm -rf plugins-fixed
            - curl -L https://www.partha.com/downloads/McGimp-2.10.6.app.zip -O
            - unzip McGimp-2.10.6.app.zip
            - rm -f /tmp/gimp.app
            - ln -s "$(pwd)/McGimp-2.10.6.app" /tmp/gimp.app
            - bash ./fix-dylib.sh ${TARGET_PLUGIN} "McGimp-2.10.6.app"
            - ls plugins-fixed
            - cd plugins-fixed
            - tar czvf ../${TARGET_PLUGIN}-McGimp-2.10.6-OSX.tgz ??*
            - cd ..
            #
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - bash  ./upload_rotate.sh "continuous" *.tgz
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
